//
//  SoShoStyleKit.h
//  SoSho
//
//  Created by AuthorName on 28.10.2014.
//  Copyright (c) 2014 SoSho. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SoShoStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNLoginWithFacebookTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNAskAFriendTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNBuyOnlineTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconInsideImageLikesTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iconInsideImageDislikesTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNLikeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNDislikeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNITargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarMessagesActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarHomeActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarWishlistActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarMoreActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarMoreInActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarMessagesInActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarWishlistInActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarHomeInActiveTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNAlertYouHaveANewMessageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* btnMainMenuTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* soshoAppLogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bTNGoBackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* roundedRectangleForHomeAndDetailPicturesTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* overlaydeletewishlistIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* wishlistRoundedRectangleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* dontDeleteKonvertiertTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* one_bar_for_detail_screenTargets;

// Drawing Methods
+ (void)drawBTNLoginWithFacebook;
+ (void)drawBTNAskAFriend;
+ (void)drawBTNBuyOnline;
+ (void)drawIconInsideImageLikes;
+ (void)drawIconInsideImageDislikes;
+ (void)drawBTNLike;
+ (void)drawBTNDislike;
+ (void)drawBTNI;
+ (void)drawTabBarMessagesActive;
+ (void)drawTabBarHomeActive;
+ (void)drawTabBarWishlistActive;
+ (void)drawTabBarMoreActive;
+ (void)drawTabBarMoreInActive;
+ (void)drawTabBarMessagesInActive;
+ (void)drawTabBarWishlistInActive;
+ (void)drawTabBarHomeInActive;
+ (void)drawBTNAlertYouHaveANewMessage;
+ (void)drawBtnMainMenu;
+ (void)drawSoshoAppLogo;
+ (void)drawBTNGoBack;
+ (void)drawRoundedRectangleForHomeAndDetailPictures;
+ (void)drawOverlaydeletewishlistIcon;
+ (void)drawWishlistRoundedRectangle;
+ (void)drawDontDeleteKonvertiert;
+ (void)drawOne_bar_for_detail_screen;

// Generated Images
+ (UIImage*)imageOfBTNLoginWithFacebook;
+ (UIImage*)imageOfBTNAskAFriend;
+ (UIImage*)imageOfBTNBuyOnline;
+ (UIImage*)imageOfIconInsideImageLikes;
+ (UIImage*)imageOfIconInsideImageDislikes;
+ (UIImage*)imageOfBTNLike;
+ (UIImage*)imageOfBTNDislike;
+ (UIImage*)imageOfBTNI;
+ (UIImage*)imageOfTabBarMessagesActive;
+ (UIImage*)imageOfTabBarHomeActive;
+ (UIImage*)imageOfTabBarWishlistActive;
+ (UIImage*)imageOfTabBarMoreActive;
+ (UIImage*)imageOfTabBarMoreInActive;
+ (UIImage*)imageOfTabBarMessagesInActive;
+ (UIImage*)imageOfTabBarWishlistInActive;
+ (UIImage*)imageOfTabBarHomeInActive;
+ (UIImage*)imageOfBTNAlertYouHaveANewMessage;
+ (UIImage*)imageOfBtnMainMenu;
+ (UIImage*)imageOfSoshoAppLogo;
+ (UIImage*)imageOfBTNGoBack;
+ (UIImage*)imageOfRoundedRectangleForHomeAndDetailPictures;
+ (UIImage*)imageOfOverlaydeletewishlistIcon;
+ (UIImage*)imageOfWishlistRoundedRectangle;
+ (UIImage*)imageOfDontDeleteKonvertiert;
+ (UIImage*)imageOfOne_bar_for_detail_screen;

@end
